services:
  kptv-weather:
    image: ghcr.io/kpirnie/kptv-weather:latest
    #image: ghcr.io/kpirnie/kptv-weather:dev
    container_name: kptv_weather
    restart: unless-stopped
    ports:
      - WHATEVER_PORT_YOU_WANT_TO_USE:8080
      
    # to utilize ffmpeg, you must have it installed on your machine and add these 2 volumes
    # make sure to change the path to where ffmpeg and ffprobe are located on your machine  
    #volumes:
      #- /YOUR/PATH/TO/ffmpeg:/usr/local/bin/ffmpeg:ro
      #- /YOUR/PATH/TO/ffprobe:/usr/local/bin/ffprobe:ro
      # you'll also need to add your machines drivers
      #- /usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri:ro
    # for hardware acceleration with ffmpeg
    #devices:
    #  - /dev/dri:/dev/dri
    # necessary for hardware support
    #group_add:
    #  - video
    #  - render


    # Health check
    healthcheck:
      test: [ "CMD", "curl", "-v", "http://127.0.0.1:8080/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
